<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        {
            $municipalities = array(
                array('code' => 'AMA-1', 'name' => 'Alto Orinoco (La Esmeralda)'),
                array('code' => 'AMA-2', 'name' => 'Atabapo (San Fernando de Atabapo)'),
                array('code' => 'AMA-3', 'name' => 'Atures (Puerto Ayacucho)'),
                array('code' => 'AMA-4', 'name' => 'Autana (Isla Ratón)'),
                array('code' => 'AMA-5', 'name' => 'Manapiare (San Juan de Manapiare)'),
                array('code' => 'AMA-6', 'name' => 'Maroa (Maroa)'),
                array('code' => 'AMA-7', 'name' => 'Río Negro (San Carlos de Río Negro)'),

                array('code' => 'ANZ-1', 'name' => 'Anaco (Anaco)'),
                array('code' => 'ANZ-2', 'name' => 'Aragua (Aragua de Barcelona)'),
                array('code' => 'ANZ-3', 'name' => 'Bolívar (Barcelona)'),
                array('code' => 'ANZ-4', 'name' => 'Bruzual (Clarines)'),
                array('code' => 'ANZ-5', 'name' => 'Cajigal (Onoto)'),
                array('code' => 'ANZ-6', 'name' => 'Carvajal (Valle de Guanape)'),
                array('code' => 'ANZ-7', 'name' => 'Freites (Cantaura)'),
                array('code' => 'ANZ-8', 'name' => 'Guanipa (San José de Guanipa)'),
                array('code' => 'ANZ-9', 'name' => 'Guanta (Guanta)'),
                array('code' => 'ANZ-10', 'name' => 'Independencia (Soledad)'),
                array('code' => 'ANZ-11', 'name' => 'Libertad (San Mateo)'),
                array('code' => 'ANZ-12', 'name' => 'Sir Arthur McGregor (El Chaparro)'),
                array('code' => 'ANZ-13', 'name' => 'Miranda (Pariaguán)'),
                array('code' => 'ANZ-14', 'name' => 'Monagas (Mapire)'),
                array('code' => 'ANZ-15', 'name' => 'Peñalver (Puerto Píritu)'),
                array('code' => 'ANZ-16', 'name' => 'Píritu (Píritu)'),
                array('code' => 'ANZ-17', 'name' => 'San Juan de Capistrano (Boca de Uchire)'),
                array('code' => 'ANZ-18', 'name' => 'Santa Ana (Santa Ana)'),
                array('code' => 'ANZ-19', 'name' => 'Simón Rodríguez (El Tigre)'),
                array('code' => 'ANZ-20', 'name' => 'Sotillo (Puerto La Cruz)'),
                array('code' => 'ANZ-21', 'name' => 'Turístico Diego Bautista Urbaneja (Lechería)'),

                array('code' => 'APU-1', 'name' => 'Achaguas (Achaguas)'),
                array('code' => 'APU-2', 'name' => 'Biruaca (Biruaca)'),
                array('code' => 'APU-3', 'name' => 'Pedro Camejo (San Juan de Payara)'),
                array('code' => 'APU-4', 'name' => 'Muñoz (Bruzual)'),
                array('code' => 'APU-5', 'name' => 'Páez (Guasdualito)'),
                array('code' => 'APU-6', 'name' => 'Rómulo Gallegos (Elorza)'),
                array('code' => 'APU-7', 'name' => 'San Fernando (San Fernando de Apure)'),

                array('code' => 'ARA-1', 'name' => 'Alcántara (Santa Rita)'),
                array('code' => 'ARA-2', 'name' => 'Bolívar (San Mateo)'),
                array('code' => 'ARA-3', 'name' => 'Camatagua (Camatagua)'),
                array('code' => 'ARA-4', 'name' => 'Girardot (Maracay)'),
                array('code' => 'ARA-5', 'name' => 'Iragorry (El Limón)'),
                array('code' => 'ARA-6', 'name' => 'Lamas (Santa Cruz de Aragua)'),
                array('code' => 'ARA-7', 'name' => 'Libertador (Palo Negro)'),
                array('code' => 'ARA-8', 'name' => 'Mariño (Turmero)'),
                array('code' => 'ARA-9', 'name' => 'Michelena (Las Tejerías)'),
                array('code' => 'ARA-10', 'name' => 'Ocumare de la Costa de Oro (Ocumare de la Costa)'),
                array('code' => 'ARA-11', 'name' => 'Revenga (El Consejo)'),
                array('code' => 'ARA-12', 'name' => 'Ribas (La Victoria)'),
                array('code' => 'ARA-13', 'name' => 'San Casimiro (San Casimiro)'),
                array('code' => 'ARA-14', 'name' => 'San Sebastián (San Sebastián de los Reyes)'),
                array('code' => 'ARA-15', 'name' => 'Sucre (Cagua)'),
                array('code' => 'ARA-16', 'name' => 'Tovar (Colonia Tovar)'),
                array('code' => 'ARA-17', 'name' => 'Urdaneta (Barbacoas)'),
                array('code' => 'ARA-18', 'name' => 'Zamora (Villa de Cura)'),

                array('code' => 'BAR-1', 'name' => 'Alberto Arvelo Torrealba (Sabaneta)'),
                array('code' => 'BAR-2', 'name' => 'Andrés Eloy Blanco (El Cantón)'),
                array('code' => 'BAR-3', 'name' => 'Antonio José de Sucre (Socopó)'),
                array('code' => 'BAR-4', 'name' => 'Arismendi (Arismendi)'),
                array('code' => 'BAR-5', 'name' => 'Barinas (Barinas)'),
                array('code' => 'BAR-6', 'name' => 'Bolívar (Barinitas)'),
                array('code' => 'BAR-7', 'name' => 'Cruz Paredes (Barrancas)'),
                array('code' => 'BAR-8', 'name' => 'Ezequiel Zamora (Santa Bárbara)'),
                array('code' => 'BAR-9', 'name' => 'Obispos (Obispos)'),
                array('code' => 'BAR-10', 'name' => 'Pedraza (Ciudad Bolivia)'),
                array('code' => 'BAR-11', 'name' => 'Rojas (Libertad)'),
                array('code' => 'BAR-12', 'name' => 'Sosa (Ciudad de Nutrias)'),

                array('code' => 'BOL-1', 'name' => 'Angostura (Ciudad Piar)'),
                array('code' => 'BOL-2', 'name' => 'Angostura del Orinoco (Ciudad Bolívar)'),
                array('code' => 'BOL-3', 'name' => 'Caroní (Ciudad Guayana)'),
                array('code' => 'BOL-4', 'name' => 'Cedeño (Caicara del Orinoco)'),
                array('code' => 'BOL-5', 'name' => 'Chien (El Palmar)'),
                array('code' => 'BOL-6', 'name' => 'El Callao (El Callao)'),
                array('code' => 'BOL-7', 'name' => 'Gran Sabana (Santa Elena de Uairén)'),
                array('code' => 'BOL-8', 'name' => 'Piar (Upata)'),
                array('code' => 'BOL-9', 'name' => 'Roscio (Guasipati)'),
                array('code' => 'BOL-10', 'name' => 'Sifontes (El Dorado)'),
                array('code' => 'BOL-11', 'name' => 'Sucre (Maripa)'),

                array('code' => 'CAR-1', 'name' => 'Bejuma (Bejuma)'),
                array('code' => 'CAR-2', 'name' => 'Carlos Arvelo (Güigüe)'),
                array('code' => 'CAR-3', 'name' => 'Diego Ibarra (Mariara)'),
                array('code' => 'CAR-4', 'name' => 'Guacara (Guacara)'),
                array('code' => 'CAR-5', 'name' => 'Juan José Mora (Morón)'),
                array('code' => 'CAR-6', 'name' => 'Libertador (Tocuyito)'),
                array('code' => 'CAR-7', 'name' => 'Los Guayos (Los Guayos)'),
                array('code' => 'CAR-8', 'name' => 'Miranda (Miranda)'),
                array('code' => 'CAR-9', 'name' => 'Montalbán (Montalbán)'),
                array('code' => 'CAR-10', 'name' => 'Naguanagua (Naguanagua)'),
                array('code' => 'CAR-11', 'name' => 'Puerto Cabello (Puerto Cabello)'),
                array('code' => 'CAR-12', 'name' => 'San Diego (San Diego)'),
                array('code' => 'CAR-13', 'name' => 'San Joaquín (San Joaquín)'),
                array('code' => 'CAR-14', 'name' => 'Valencia (Valencia)'),

                array('code' => 'COJ-1', 'name' => 'Anzoátegui (Cojedes)'),
                array('code' => 'COJ-2', 'name' => 'San Carlos (San Carlos)'),
                array('code' => 'COJ-3', 'name' => 'Girardot (El Baúl)'),
                array('code' => 'COJ-4', 'name' => 'Lima Blanco (Macapo)'),
                array('code' => 'COJ-5', 'name' => 'Pao de San Juan Bautista (El Pao)'),
                array('code' => 'COJ-6', 'name' => 'Ricaurte (Libertad)'),
                array('code' => 'COJ-7', 'name' => 'Rómulo Gallegos (Las Vegas)'),
                array('code' => 'COJ-8', 'name' => 'Tinaco (Tinaco)'),
                array('code' => 'COJ-9', 'name' => 'Tinaquillo (Tinaquillo)'),

                array('code' => 'DA-1', 'name' => 'Antonio Díaz (Curiapo)'),
                array('code' => 'DA-2', 'name' => 'Casacoima (Sierra Imataca)'),
                array('code' => 'DA-3', 'name' => 'Pedernales (Pedernales)'),
                array('code' => 'DA-4', 'name' => 'Tucupita (Tucupita)'),

                array('code' => 'DC-1', 'name' => 'Libertador (Caracas)'),

                array('code' => 'FAL-1', 'name' => 'Acosta (San Juan de los Cayos)'),
                array('code' => 'FAL-2', 'name' => 'Bolívar (San Luis)'),
                array('code' => 'FAL-3', 'name' => 'Buchivacoa (Capatárida)'),
                array('code' => 'FAL-4', 'name' => 'Carirubana (Punto Fijo)'),
                array('code' => 'FAL-5', 'name' => 'Colina (La Vela de Coro)'),
                array('code' => 'FAL-6', 'name' => 'Dabajuro (Dabajuro)'),
                array('code' => 'FAL-7', 'name' => 'Democracia (Pedregal)'),
                array('code' => 'FAL-8', 'name' => 'Falcón (Pueblo Nuevo)'),
                array('code' => 'FAL-9', 'name' => 'Federación (Churuguara)'),
                array('code' => 'FAL-10', 'name' => 'Iturriza (Chichiriviche)'),
                array('code' => 'FAL-11', 'name' => 'Jacura (Jacura)'),
                array('code' => 'FAL-12', 'name' => 'Los Taques (Santa Cruz de Los Taques)'),
                array('code' => 'FAL-13', 'name' => 'Manaure (Yaracal)'),
                array('code' => 'FAL-14', 'name' => 'Mauroa (Mene de Mauroa)'),
                array('code' => 'FAL-15', 'name' => 'Miranda (Santa Ana de Coro)'),
                array('code' => 'FAL-16', 'name' => 'Palmasola (Palmasola)'),
                array('code' => 'FAL-17', 'name' => 'Petit (Cabure)'),
                array('code' => 'FAL-18', 'name' => 'Píritu (Píritu)'),
                array('code' => 'FAL-19', 'name' => 'San Francisco (Mirimire)'),
                array('code' => 'FAL-20', 'name' => 'Sucre (La Cruz de Taratara)'),
                array('code' => 'FAL-21', 'name' => 'Silva (Tucacas)'),
                array('code' => 'FAL-22', 'name' => 'Tocópero (Tocópero)'),
                array('code' => 'FAL-23', 'name' => 'Unión (Santa Cruz de Bucaral)'),
                array('code' => 'FAL-24', 'name' => 'Urumaco (Urumaco)'),
                array('code' => 'FAL-25', 'name' => 'Zamora (Puerto Cumarebo)'),

                array('code' => 'GUA-1', 'name' => 'Camaguán (Camaguán)'),
                array('code' => 'GUA-2', 'name' => 'Chaguaramas (Chaguaramas)'),
                array('code' => 'GUA-3', 'name' => 'El Socorro (El Socorro)'),
                array('code' => 'GUA-4', 'name' => 'Francisco de Miranda (Calabozo)'),
                array('code' => 'GUA-5', 'name' => 'José Félix Ribas (Tucupido)'),
                array('code' => 'GUA-6', 'name' => 'José Tadeo Monagas (Altagracia de Orituco)'),
                array('code' => 'GUA-7', 'name' => 'Juan Germán Roscio (San Juan de los Morros)'),
                array('code' => 'GUA-8', 'name' => 'Juan José Rondón (Las Mercedes)'),
                array('code' => 'GUA-9', 'name' => 'Julián Mellado (El Sombrero)'),
                array('code' => 'GUA-10', 'name' => 'Leonardo Infante (Valle de La Pascua)'),
                array('code' => 'GUA-11', 'name' => 'Ortiz (Ortiz)'),
                array('code' => 'GUA-12', 'name' => 'San Gerónimo de Guayabal (Guayabal)'),
                array('code' => 'GUA-13', 'name' => 'San José de Guaribe (San José de Guaribe)'),
                array('code' => 'GUA-14', 'name' => 'Santa María de Ipire (Santa María de Ipire)'),
                array('code' => 'GUA-15', 'name' => 'Zaraza (Zaraza)'),

                array('code' => 'LAR-1', 'name' => 'Andrés Eloy Blanco (Sanare)'),
                array('code' => 'LAR-2', 'name' => 'Crespo (Duaca)'),
                array('code' => 'LAR-3', 'name' => 'Iribarren (Barquisimeto)'),
                array('code' => 'LAR-4', 'name' => 'Jiménez (Quibor)'),
                array('code' => 'LAR-5', 'name' => 'Morán (El Tocuyo)'),
                array('code' => 'LAR-6', 'name' => 'Palavecino (Cabudare)'),
                array('code' => 'LAR-7', 'name' => 'Simón Planas (Sarare)'),
                array('code' => 'LAR-8', 'name' => 'Torres (Carora)'),
                array('code' => 'LAR-9', 'name' => 'Urdaneta (Siquisique)'),
                array('code' => 'LAR-10', 'name' => 'Vargas (La Guaira)'),

                array('code' => 'MER-1', 'name' => 'Alberto Adriani (El Vigía)'),
                array('code' => 'MER-2', 'name' => 'Andrés Bello (La Azulita)'),
                array('code' => 'MER-3', 'name' => 'Antonio Pinto Salinas (Santa Cruz de Mora)'),
                array('code' => 'MER-4', 'name' => 'Aricagua (Aricagua)'),
                array('code' => 'MER-5', 'name' => 'Arzobispo Chacón (Canaguá)'),
                array('code' => 'MER-6', 'name' => 'Campo Elías (Ejido)'),
                array('code' => 'MER-7', 'name' => 'Caracciolo Parra Olmedo (Tucaní)'),
                array('code' => 'MER-8', 'name' => 'Cardenal Quintero (Santo Domingo)'),
                array('code' => 'MER-9', 'name' => 'Guaraque (Guaraque)'),
                array('code' => 'MER-10', 'name' => 'Julio Cesar Salas (Arapuey)'),
                array('code' => 'MER-11', 'name' => 'Justo Briceño (Torondoy)'),
                array('code' => 'MER-12', 'name' => 'Libertador (Mérida)'),
                array('code' => 'MER-13', 'name' => 'Miranda (Timotes)'),
                array('code' => 'MER-14', 'name' => 'Obispo Ramos de Lora (Santa Elena de Arenales)'),
                array('code' => 'MER-15', 'name' => 'Padre Noguera (Santa María de Caparo)'),
                array('code' => 'MER-16', 'name' => 'Pueblo Llano (Pueblo Llano)'),
                array('code' => 'MER-17', 'name' => 'Rangel (Mucuchíes)'),
                array('code' => 'MER-18', 'name' => 'Rivas Dávila (Bailadores)'),
                array('code' => 'MER-19', 'name' => 'Santos Marquina (Tabay)'),
                array('code' => 'MER-20', 'name' => 'Sucre (Lagunillas)'),
                array('code' => 'MER-21', 'name' => 'Tovar (Tovar)'),
                array('code' => 'MER-22', 'name' => 'Tulio Febres Cordero (Nueva Bolivia)'),
                array('code' => 'MER-23', 'name' => 'Zea (Zea)'),

                array('code' => 'MIR-1', 'name' => 'Acevedo (Caucagua)'),
                array('code' => 'MIR-2', 'name' => 'Andrés Bello (San José de Barlovento)'),
                array('code' => 'MIR-3', 'name' => 'Baruta (Baruta)'),
                array('code' => 'MIR-4', 'name' => 'Bolívar (San Francisco de Yare)'),
                array('code' => 'MIR-5', 'name' => 'Brión (Higuerote)'),
                array('code' => 'MIR-6', 'name' => 'Buroz (Mamporal)'),
                array('code' => 'MIR-7', 'name' => 'Carrizal (Carrizal)'),
                array('code' => 'MIR-8', 'name' => 'Chacao (Chacao)'),
                array('code' => 'MIR-9', 'name' => 'Cristóbal Rojas (Charallave)'),
                array('code' => 'MIR-10', 'name' => 'El Hatillo (El Hatillo)'),
                array('code' => 'MIR-11', 'name' => 'Guaicaipuro (Los Teques)(El Jarillo)'),
                array('code' => 'MIR-12', 'name' => 'Gual (Cúpira)'),
                array('code' => 'MIR-13', 'name' => 'Independencia (Santa Teresa del Tuy)'),
                array('code' => 'MIR-14', 'name' => 'Lander (Ocumare del Tuy)'),
                array('code' => 'MIR-15', 'name' => 'Los Salias (San Antonio de los Altos)'),
                array('code' => 'MIR-16', 'name' => 'Páez (Río Chico)'),
                array('code' => 'MIR-17', 'name' => 'Paz Castillo'),
                array('code' => 'MIR-18', 'name' => 'Plaza (Guarenas)'),
                array('code' => 'MIR-19', 'name' => 'Sucre (Petare)'),
                array('code' => 'MIR-20', 'name' => 'Urdaneta (Cúa)'),
                array('code' => 'MIR-21', 'name' => 'Zamora (Guatire)'),

                array('code' => 'MON-1', 'name' => 'Acosta (San Antonio de Capayacuar)'),
                array('code' => 'MON-2', 'name' => 'Aguasay (Aguasay)'),
                array('code' => 'MON-3', 'name' => 'Bolívar (Caripito)'),
                array('code' => 'MON-4', 'name' => 'Caripe (Caripe)'),
                array('code' => 'MON-5', 'name' => 'Cedeño (Caicara de Maturín)'),
                array('code' => 'MON-6', 'name' => 'Libertador (Temblador)'),
                array('code' => 'MON-7', 'name' => 'Maturín (Maturín)'),
                array('code' => 'MON-8', 'name' => 'Piar (Aragua de Maturín)'),
                array('code' => 'MON-9', 'name' => 'Punceres (Quiriquire)'),
                array('code' => 'MON-10', 'name' => 'Santa Bárbara (Santa Bárbara)'),
                array('code' => 'MON-11', 'name' => 'Sotillo (Barrancas del Orinoco)'),
                array('code' => 'MON-12', 'name' => 'Uracoa (Uracoa)'),
                array('code' => 'MON-13', 'name' => 'Zamora (Punta de Mata)'),

                array('code' => 'NE-1', 'name' => 'Antolín del Campo (La Plaza de Paraguachí)'),
                array('code' => 'NE-2', 'name' => 'Antonio Díaz (San Juan Bautista)'),
                array('code' => 'NE-3', 'name' => 'Arismendi (La Asunción)'),
                array('code' => 'NE-4', 'name' => 'García (El Valle)'),
                array('code' => 'NE-5', 'name' => 'Gómez (Santa Ana)'),
                array('code' => 'NE-6', 'name' => 'Macanao (Boca de Río)'),
                array('code' => 'NE-7', 'name' => 'Maneiro (Pampatar)'),
                array('code' => 'NE-8', 'name' => 'Marcano (Juan Griego)'),
                array('code' => 'NE-9', 'name' => 'Mariño (Porlamar)'),
                array('code' => 'NE-10', 'name' => 'Tubores (Punta de Piedras)'),
                array('code' => 'NE-11', 'name' => 'Villalba (San Pedro de Coche)'),

                array('code' => 'POR-1', 'name' => 'Agua Blanca (Agua Blanca)'),
                array('code' => 'POR-2', 'name' => 'Araure (Araure)'),
                array('code' => 'POR-3', 'name' => 'Esteller (Píritu)'),
                array('code' => 'POR-4', 'name' => 'Guanare (Guanare)'),
                array('code' => 'POR-5', 'name' => 'Guanarito (Guanarito)'),
                array('code' => 'POR-6', 'name' => 'José Vicente de Unda (Chabasquén)'),
                array('code' => 'POR-7', 'name' => 'Ospino (Ospino)'),
                array('code' => 'POR-8', 'name' => 'Páez (Acarigua)'),
                array('code' => 'POR-9', 'name' => 'Papelón (Papelón)'),
                array('code' => 'POR-10', 'name' => 'San Genaro de Boconoíto (Boconoíto)'),
                array('code' => 'POR-11', 'name' => 'San Rafael de Onoto (San Rafael de Onoto)'),
                array('code' => 'POR-12', 'name' => 'Santa Rosalía (El Playón)'),
                array('code' => 'POR-13', 'name' => 'Sucre (Biscucuy)'),
                array('code' => 'POR-14', 'name' => 'Turén (Villa Bruzual)'),

                array('code' => 'SUC-1', 'name' => 'Andrés Eloy Blanco (Casanay)'),
                array('code' => 'SUC-2', 'name' => 'Andrés Mata (San José de Aerocuar)'),
                array('code' => 'SUC-3', 'name' => 'Arismendi (Río Caribe)'),
                array('code' => 'SUC-4', 'name' => 'Benítez (El Pilar)'),
                array('code' => 'SUC-5', 'name' => 'Bermúdez (Carúpano)'),
                array('code' => 'SUC-6', 'name' => 'Bolívar (Marigüitar)'),
                array('code' => 'SUC-7', 'name' => 'Cajigal (Yaguaraparo)'),
                array('code' => 'SUC-8', 'name' => 'Cruz Salmerón Acosta (Araya)'),
                array('code' => 'SUC-9', 'name' => 'Libertador (Tunapuy)'),
                array('code' => 'SUC-10', 'name' => 'Mariño (Irapa)'),
                array('code' => 'SUC-11', 'name' => 'Mejía (San Antonio del Golfo)'),
                array('code' => 'SUC-12', 'name' => 'Montes (Cumanacoa)'),
                array('code' => 'SUC-13', 'name' => 'Ribero (Cariaco)'),
                array('code' => 'SUC-14', 'name' => 'Sucre (Cumaná)'),
                array('code' => 'SUC-15', 'name' => 'Valdez (Güiria)'),

                array('code' => 'TAC-1', 'name' => 'Andrés Bello (Cordero)'),
                array('code' => 'TAC-2', 'name' => 'Antonio Rómulo Costa (Las Mesas)'),
                array('code' => 'TAC-3', 'name' => 'Ayacucho (Colón)'),
                array('code' => 'TAC-4', 'name' => 'Bolívar (San Antonio del Táchira)'),
                array('code' => 'TAC-5', 'name' => 'Cárdenas (Táriba)'),
                array('code' => 'TAC-6', 'name' => 'Córdoba (Santa Ana de Táchira)'),
                array('code' => 'TAC-7', 'name' => 'Fernández (San Rafael del Piñal)'),
                array('code' => 'TAC-8', 'name' => 'Francisco de Miranda (San José de Bolívar)'),
                array('code' => 'TAC-9', 'name' => 'García de Hevia (La Fría)'),
                array('code' => 'TAC-10', 'name' => 'Guásimos (Palmira)'),
                array('code' => 'TAC-11', 'name' => 'Independencia (Capacho Nuevo)'),
                array('code' => 'TAC-12', 'name' => 'Jáuregui (La Grita)'),
                array('code' => 'TAC-13', 'name' => 'José María Vargas (El Cobre)'),
                array('code' => 'TAC-14', 'name' => 'Junín (Rubio)'),
                array('code' => 'TAC-15', 'name' => 'Libertad (Capacho Viejo)'),
                array('code' => 'TAC-16', 'name' => 'Libertador (Abejales)'),
                array('code' => 'TAC-17', 'name' => 'Lobatera (Lobatera)'),
                array('code' => 'TAC-18', 'name' => 'Michelena (Michelena)'),
                array('code' => 'TAC-19', 'name' => 'Panamericano (Coloncito)'),
                array('code' => 'TAC-20', 'name' => 'Pedro María Ureña (Ureña)'),
                array('code' => 'TAC-21', 'name' => 'Rafael Urdaneta (Delicias)'),
                array('code' => 'TAC-22', 'name' => 'Samuel Dario Maldonado (La Tendida)'),
                array('code' => 'TAC-23', 'name' => 'San Cristóbal (San Cristóbal)'),
                array('code' => 'TAC-24', 'name' => 'San Judas Tadeo (Umuquena)'),
                array('code' => 'TAC-25', 'name' => 'Seboruco (Seboruco)'),
                array('code' => 'TAC-26', 'name' => 'Simón Rodríguez (San Simón)'),
                array('code' => 'TAC-27', 'name' => 'Sucre (Queniquea)'),
                array('code' => 'TAC-28', 'name' => 'Torbes (San Josecito)'),
                array('code' => 'TAC-29', 'name' => 'Uribante (Pregonero)'),

                array('code' => 'TRU-1', 'name' => 'Andrés Bello (Santa Isabel)'),
                array('code' => 'TRU-2', 'name' => 'Boconó (Boconó)'),
                array('code' => 'TRU-3', 'name' => 'Bolívar (Sabana Grande)'),
                array('code' => 'TRU-4', 'name' => 'Candelaria (Chejendé)'),
                array('code' => 'TRU-5', 'name' => 'Carache (Carache)'),
                array('code' => 'TRU-6', 'name' => 'Carvajal (Carvajal)'),
                array('code' => 'TRU-7', 'name' => 'Escuque (Escuque)'),
                array('code' => 'TRU-8', 'name' => 'Juan Vicente Campo Elías (Campo Elías)'),
                array('code' => 'TRU-9', 'name' => 'La Ceiba (Santa Apolonia)'),
                array('code' => 'TRU-10', 'name' => 'Márquez Cañizales (El Paradero)'),
                array('code' => 'TRU-11', 'name' => 'Miranda (El Dividive)'),
                array('code' => 'TRU-12', 'name' => 'Monte Carmelo (Monte Carmelo)'),
                array('code' => 'TRU-13', 'name' => 'Motatán (Motatán)'),
                array('code' => 'TRU-14', 'name' => 'Motatán (Motatán)'),
                array('code' => 'TRU-15', 'name' => 'Pampanito (Pampanito)'),
                array('code' => 'TRU-16', 'name' => 'Rangel (Betijoque)'),
                array('code' => 'TRU-17', 'name' => 'Sucre (Sabana de Mendoza)'),
                array('code' => 'TRU-18', 'name' => 'Trujillo (Trujillo)'),
                array('code' => 'TRU-19', 'name' => 'Urdaneta (La Quebrada)'),
                array('code' => 'TRU-20', 'name' => 'Valera (Valera)'),

                array('code' => 'YAR-1', 'name' => 'Arístides Bastidas (San Pablo)'),
                array('code' => 'YAR-2', 'name' => 'Bolívar (Aroa)'),
                array('code' => 'YAR-3', 'name' => 'Bruzual (Chivacoa)'),
                array('code' => 'YAR-4', 'name' => 'Cocorote (Cocorote)'),
                array('code' => 'YAR-5', 'name' => 'Independencia (Independencia)'),
                array('code' => 'YAR-6', 'name' => 'José Antonio Páez (Sabana de Parra)'),
                array('code' => 'YAR-7', 'name' => 'La Trinidad (Boraure)'),
                array('code' => 'YAR-8', 'name' => 'Manuel Monge (Yumare)'),
                array('code' => 'YAR-9', 'name' => 'Nirgua (Nirgua)'),
                array('code' => 'YAR-10', 'name' => 'Peña (Yaritagua)'),
                array('code' => 'YAR-11', 'name' => 'San Felipe (San Felipe)'),
                array('code' => 'YAR-12', 'name' => 'Sucre (Guama)'),
                array('code' => 'YAR-13', 'name' => 'Urachiche (Urachiche)'),
                array('code' => 'YAR-14', 'name' => 'Veroes (Farriar)'),

                array('code' => 'ZUL-1', 'name' => 'Almirante Padilla (El Toro)'),
                array('code' => 'ZUL-2', 'name' => 'Baralt (San Timoteo)'),
                array('code' => 'ZUL-3', 'name' => 'Cabimas (Cabimas)'),
                array('code' => 'ZUL-4', 'name' => 'Catatumbo (Encontrados)'),
                array('code' => 'ZUL-5', 'name' => 'Colón (San Carlos del Zulia)'),
                array('code' => 'ZUL-6', 'name' => 'Francisco Javier Pulgar (Pueblo Nuevo-El Chivo)'),
                array('code' => 'ZUL-7', 'name' => 'Guajira (Sinamaica)'),
                array('code' => 'ZUL-8', 'name' => 'Jesús Enrique Lossada (La Concepción)'),
                array('code' => 'ZUL-9', 'name' => 'Jesús María Semprún (Casigua El Cubo)'),
                array('code' => 'ZUL-10', 'name' => 'La Cañada de Urdaneta (Concepción)'),
                array('code' => 'ZUL-11', 'name' => 'Lagunillas (Ciudad Ojeda)'),
                array('code' => 'ZUL-12', 'name' => 'Machiques de Perijá (Machiques)'),
                array('code' => 'ZUL-13', 'name' => 'Mara (San Rafael del Moján)'),
                array('code' => 'ZUL-14', 'name' => 'Maracaibo (Maracaibo)'),
                array('code' => 'ZUL-15', 'name' => 'Miranda (Los Puertos de Altagracia)'),
                array('code' => 'ZUL-16', 'name' => 'Rosario de Perijá (La Villa del Rosario)'),
                array('code' => 'ZUL-17', 'name' => 'San Francisco (San Francisco)'),
                array('code' => 'ZUL-18', 'name' => 'Santa Rita (Santa Rita)'),
                array('code' => 'ZUL-19', 'name' => 'Simón Bolívar (Tía Juana)'),
                array('code' => 'ZUL-20', 'name' => 'Sucre (Bobures)'),
                array('code' => 'ZUL-21', 'name' => 'Valmore Rodríguez (Bachaquero)'),
            );
    
            DB::table('municipalities')->insert($municipalities);
        }
    }
}
